[package]
name = "reefvolt-bridge"
version = "0.1.0"
edition = "2021"
license = "LGPL"


[[bin]]
name = "rv-cmd"

[[bin]]
name = "reefvolt-bridge"


[dependencies]
rusb = "0.9"
log = "0.4"
env_logger = "0.9"
anyhow = "1"
packed_struct = "0.10"
thiserror = "1"
chrono = "0.4"
